export const CHANGE_NICKNAME_VALUE = 'register/CHANGE_NICKNAME_VALUE';
export const TOGGLE_NICKNAME_FOCUS = 'register/TOGGLE_NICKNAME_FOCUS';
export const CHANGE_NICKNAME_VALIDATE_RESULT = 'register/CHANGE_NICKNAME_VALIDATERESULT';

export const CHANGE_PHONE_VALUE = 'register/CHANGE_PHONE_VALUE';
export const CHANGE_PHONE_VALIDATE_RESULT = 'register/CHANGE_PHONE_VALIDATE_RESULT';
export const TOGGLE_PHONE_FOCUS = 'register/TOGGLE_PHONE_FOCUS';

export const CHANGE_VERIFICATION_VALUE = 'register/CHANGE_VERIFICATION_VALUE';
export const CHANGE_VERIFICATION_DISABLE = 'register/CHANGE_VERIFICATION_DISABLE';

export const CHANGE_PASSWORD = 'register/CHANGE_PASSWORD';
export const FOCUS_PASSWORD = 'register/FOCUS_PASSWORD';
export const BLUR_PASSWORD = 'register/BLUR_PASSWORD';