export const CHANGE_ERR_TIP = 'register/CHANGE_ERR_TIP';
export const TOGGLE_ERR_TIP = 'register/TOGGLE_ERR_TIP';

export const CHANGE_NICKNAME_VALUE = 'register/CHANGE_NICKNAME_VALUE';
export const TOGGLE_NICKNAME_FOCUS = 'register/TOGGLE_NICKNAME_FOCUS';
export const CHANGE_NICKNAME_VALIDATE_RESULT = 'register/CHANGE_NICKNAME_VALIDATERESULT';

export const CHANGE_PHONE_VALUE = 'register/CHANGE_PHONE_VALUE';
export const CHANGE_PHONE_VALIDATE_RESULT = 'register/CHANGE_PHONE_VALIDATE_RESULT';
export const TOGGLE_PHONE_FOCUS = 'register/TOGGLE_PHONE_FOCUS';

export const CHANGE_VERIFICATION_VALUE = 'register/CHANGE_VERIFICATION_VALUE';
export const CHANGE_VERIFICATION_DISABLE = 'register/CHANGE_VERIFICATION_DISABLE';
export const TOGGLE_VERIFICATION_FOCUS = 'register/TOGGLE_VERIFICATION_FOCUS';
export const CHANGE_VERIFICATION_VALIDATE_RESULT = 'register/CHANGE_VERIFICATION_VALIDATE_RESULT';
export const CHANGE_COUNTDOWN = 'register/CHANGE_COUNTDOWN';

export const CHANGE_PASSWORD_VALUE = 'register/CHANGE_PASSWORD_VALUE';
export const CHANGE_PASSWORD_VALIDATE_RESULT = 'register/CHANGE_PASSWORD_VALIDATE_RESULT';
export const TOGGLE_PASSWORD_FOCUS = 'register/TOGGLE_PASSWORD_FOCUS';