const ON = 'ON';
const OFF = 'OFF';
const SIM_SUN = 'SIM_SUN';
const SIM_HEI = 'SIM_HEI';
const SIMPLIFIED = 'SIMPLIFIED';
const TRADITIONAL = 'TRADITIONAL';

export { ON, OFF, SIM_SUN, SIM_HEI, SIMPLIFIED, TRADITIONAL };